version: "3"
services:
  configserver:
    build: configserver
    ports:
      - "8888:8888"
    networks:
      - internal

  vault:
    image: vault
    ports:
      - "8200:8200"
    volumes:
      - "./vault/policies:/vault/policies"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_TOKEN=myroot
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    networks:
      - internal

  postgres-db:
    build: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - VAULT_TOKEN=myroot
    volumes:
      - "./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
      - "./postgres/pagila-data.sql:/docker-entrypoint-initdb.d/dump/pagila-data.sql"
      - "./postgres/pagila-schema.sql:/docker-entrypoint-initdb.d/dump/pagila-schema.sql"
      - "./postgres/init.sh:/docker-entrypoint-initdb.d/a1.sh"
    depends_on:
      - vault
    networks:
      internal:
  webapp:
    build: webapp
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - internal
    environment:
      - VAULT_TOKEN=myroot
networks:
  internal:
    driver: bridge
